name: Build Docker image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
